[package]
name = "kzg-commitment"
version = "0.1.3"
authors = ["CleanPegasus <me@cleanpegasus.dev>"]
description = "A simple crate to perform KZG polynomial commitment scheme"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = "=0.4.2"
ark-test-curves = "0.4.2"
ark-std = "0.4.0"
ark-bls12-381 = "0.4.0"
ark-poly = "0.4.2"
ark-ec = "0.4.2"
rand = "0.8.5"
derive_more = "0.99.17"
num-bigint = "0.4.6"